apiVersion: v1
kind: Service
metadata:
  name: goecho
  namespace: namespace-workflow-1726778069399
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: goecho
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80